# Question: 
https://projecteuler.net/problem=15

In [6]:
from utils.matrix import MatrixTraversal
import numpy as np


grid_size = (2+1,2+1)
grid = np.ones(grid_size)
print(grid)
# Have look ahead of 2 since having 1 returns "cannot_go_x" as Fasle even when you're in corner
p = MatrixTraversal(grid, 2)

already_visited = [[[0, 1], [0, 2], [1, 2], [2, 2]]]
current_path = []
start = [0,0] #
end = [2,2] #
current = start


while True:
    if not p.cannot_go_right(current) and current_path not in already_visited:
        current = [current[0], current[1]+1]
        current_path.append(current)
        print("going right to", current)
        continue

    if not p.cannot_go_down(current) and current_path not in already_visited:
        current = [current[0]+1, current[1]]
        print("going down to", current)
        current_path.append(current)
        continue
    else:
        already_visited.append(current_path)
        print(already_visited)
        break


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
going right to [0, 1]
going right to [0, 2]
going down to [1, 2]
going down to [2, 2]
[[[0, 1], [0, 2], [1, 2], [2, 2]], [[0, 1], [0, 2], [1, 2], [2, 2]]]
